# Generated by Django 2.1.7 on 2019-03-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['due_time']},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_time',
            field=models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
    ]
